Locales["no"] = {
["no_vehicle_nearby"] = "Ingen kjøretøy i nærheten",
["not_enough_money"] = "Du har ikke nok penger",
["job_end_afk"] = "Jobben er avsluttet på grunn av inaktivitet",
["removed_inactivity"] = "Du ble fjernet fra gruppa på grunn av inaktivitet",
["player_removed_inactivity"] = "En spiller ble fjernet fra gruppa på grunn av inaktivitet",
["too_far"] = "Du er for langt unna jordet",
["start_job_blip"] = "Start jobb",
["job_label"] = "Bonde",
["job_description"] = "Høst avlingene fra hvert jorde og last dem inn i kjøretøyet ditt. Transporter så avlingen til markedet",
["vehicle_on_field"] = "Kjøretøyet ditt står på jordet!",
["crops_not_ready"] = "Disse avlingene er ikke klare til å høstes",
["field_collected"] = "Du har høstet nok avlinger fra dette jordet",
["sell_crops_blip"] = "Selg avlinger",
["sell_crops"] = "Du har samlet inn alle avlingene, nå kan du selge dem",
["no_crops"] = "Du har ingen avlinger å selge!",
["get_crops_standalone"] = "Trykk ~INPUT_CONTEXT~ for å hente avlinger",
["get_crops"] = "Hent avlinger",
["end_job_first"] = "Du må fullføre jobben før du kan legge til nye spillere",
["collect_all_crops_first"] = "Du må samle inn alle avlingene! (%s igjen)",
["put_crate_standalone"] = "Trykk ~INPUT_CONTEXT~ for å sette ned kassa",
["put_crate_veh"] = "Sett ned kassa",
["sell_crops_standalone"] = "Trykk ~INPUT_CONTEXT~ for å selge avlinger",
["sell_crops_target"] = "Selg avlinger",
["need_jobclothes"] = "Du må ha på deg arbeidsklær",

}