Locales['no'] = {
    interact_button = '[E] ',
    interact = 'Bruk',
    open_shop = 'Åpne butikk',
    remove = 'Fjern',

    disabled_area = 'Du kan ikke plassere noe her',

    not_required_items = 'Du har ikke de nødvendige gjenstandene',
    not_enough_items = 'Du har ikke nok gjenstander',
    successfully_bagged = 'Du pakket %sx %s',
    processing = 'Behandler...',
    cooking = 'Koker...',
    need_item_amount = 'Du trenger %sx %s',

    help_move_items = 'Klikk og dra gjenstander for å flytte dem',
    help_rotate_bottle = 'Bruk musehjulet for å rotere flasker',
    help_pour_into_flask = 'Vipp flasken over kolben for å helle innholdet',
    help_stir_mixture = 'Klikk på kolben for å røre blandingen',
    help_heat_mixture = 'Klikk på varmeren for å varme blandingen',
    help_press_material = 'Klikk på materialet for å begynne pressing',
    help_collect_product = 'Klikk på produktet for å hente det',
    help_plant_seed = 'Plasser frøet i potta',
    help_pour_water = 'Hell vann i potta',
    help_add_to_mixer = 'Legg ingrediensene i mikseren',
    help_put_in_bag = 'Legg stoffene i posen',
    help_add_to_cauldron = 'Legg gjenstandene i gryta',
    help_hammer_substance = 'Bruk hammeren for å knuse stoffet',

    sell_drugs = 'Tilby narkotika',
    drug_sale_success = 'Du solgte %sx %s for %s€',
    drug_sale_failure = 'Personen avslo tilbudet ditt',
    already_sold_drugs = 'Denne personen ønsker ikke å kjøpe narkotika',
    male = 'Mann',
    female = 'Kvinne',
    drugs_sold = 'En %s selger narkotika ved %s',
    drugs_sold_title = 'Narkotikasalg',
    not_enough_police = 'Du kan ikke selge narkotika akkurat nå',

    favorite_effects = 'Favoritteffekter',
    amount_to_sell = 'Mengde å selge:',
    total_price = 'Totalpris:',
    success_chance = 'Sjanse for suksess:',
    high_risk_warning = 'Høy risiko for avslag eller politioppmerksomhet',
    offer_deal = 'Tilby avtale',

    not_enough_money = 'Du har ikke nok kontanter',
    purchase_successful = 'Du kjøpte varer for %skr',

    drug_deal = 'Narkotikaavtale',
    negotiating_with = 'Forhandler med %s',

    mixer = 'Mikser',
    selected_items = 'Valgte gjenstander:',
    clear_all_items = 'Fjern alle gjenstander',
    available_ingredients = 'Tilgjengelige ingredienser',
    max_items_selected = 'Maksimalt antall valgte gjenstander',
    no_compatible_ingredients = 'Ingen kompatible ingredienser tilgjengelig',
    no_ingredients_available = 'Ingen ingredienser tilgjengelig',
    ready_to_mix = 'Klar til å blande',
    start_mixing_instruction = 'Start blanding ved å klikke på knappen under',
    start_mixing = 'Start blanding',

    plant = 'Plante',
    water_level = 'Vannivå',
    fertilizer_level = 'Gjødselnivå',
    growth_stage = 'Vekststadium',
    water_plant = 'Vann planten',
    fertilize_plant = 'Gjødsle planten',
    close = 'Lukk',
    harvest_plant = 'Høst planten',
    ready_to_harvest = 'Klar for høsting',
    no_plant_nearby = 'Ingen plante i nærheten',

    shop = 'Butikk',
    cart_summary = 'Handlekurv-oppsummering',
    purchase_all = 'Kjøp alt (%skr)',
    cart_amount = '%skr',

    value_with_currency = '%skr',

    webhook_title = 'TK_NARKOTIKA',
    webhook_cheater = '**MULIG JUKSER**\n**Identifikatorer:** %s\n**Handling:** %s',
    webhook_action = '**HANDLING**\n**Identifikatorer:** %s\n**Handling:** %s\n**Data:** %s',

}
