Locales = Locales or {}

Locales["no"] = {
  back = "Tilbake",
  previous = "Forrige",
  next = "Neste",
  search = "Søk",
  page = "Side",
  of = "av",
  every = "hver",
  show = "Vis",
  delete = "Slett",
  copied = "Kopiert",
  copyToClipboard = "Kopier til utklippstavle",
  searchHandling = "Søk i kjøreegenskaper",
  viewChanges = "Vis endringer",
  applyHandling = "Bruk kjøreegenskaper",
  clearChanges = "Fjern endringer",
  preview = "Forhåndsvisning",
  applied = "Brukt",
  apply = "Bruk",
  exportTo = "Eksporter til:",
  overwrite = "Overskriv",
  modify = "Endre",
  configType = "Konfigurasjonstype:",
  configForTuningLua = "Konfigurasjon for config.tuning.lua:",
  xml = "XML:",
  deleting = "Sletter...",
  successfullyLoaded = "lastet inn vellykket",
  loadProfile = "Last inn profil",
  name = "Navn",
  vehicleName = "Kjøretøynavn",
  editedAt = "Opprettet",
  editedBy = "Opprettet av",
  resetHandlingToStock = "Tilbakestill kjøreegenskaper til standard",
  resetHandling = "Tilbakestill kjøreegenskaper",
  vehicleReset = "Kjøretøy tilbakestilt til standard",
  profileName = "Profilnavn",
  saving = "Lagrer...",
  save = "Lagre",
  saveAsProfile = "Lagre som profil",
  discardChanges = "Forkast endringer",
  advancedEditor = "Avansert redigeringsverktøy",
  simplifiedEditor = "Forenklet redigeringsverktøy",
  export = "Eksporter",
  savedProfiles = "Lagrede profiler",
  resetToDefault = "Tilbakestill til standard",
  handlingPreviewMode = "Forhåndsvisningsmodus for kjøreegenskaper",
  selectMechanicMode = "Velg mekanikermodus",
  processing = "Behandler...",
  confirm = "Bekreft",
  currentHandling = "Nåværende kjøreegenskaper",
  ignoreServicing = "Ignorer service",
  useBaseHandling = "Bruk grunnleggende kjøreegenskaper",
  timingToolReset = "TILBAKESTILL",
  noPresetSelected = "Ingen forhåndsinnstilling valgt",
  applyTemporarily = "Bruk midlertidig (til kjøretøyet despawner)",
  applyToPlate = "Bruk alltid på dette kjøretøyskiltet (lagres i DB)",
  applyToModel = "Bruk alltid på alle kjøretøy av denne modellen (lagres i DB)",
  handlingApplyType = "Hvordan vil du bruke disse kjøreegenskapene?",
  

  -- Long Messages
  applyHandlingIfJGMechanic = "Hvis du bruker JG Mechanic, vil disse endringene overskrive, og skadeservice vil ikke bli brukt før kjøretøyet er tilbakestilt.",
noHandlingChanges = "Det er ingen endringer i kjøreegenskapene!",
confirmationDeleteProfile = "Er du sikker på at du vil slette denne profilen?",
resetHandlingToStockMsg = "Dette kjøretøyet har fått kjøreegenskapene redigert av dette verktøyet. Du kan tilbakestille kjøretøyet til standard (profilen det hadde før denne redigeringen) ved å klikke på knappen nedenfor. Hvis kjøreegenskapene er lagret i databasen, vil dataene bli slettet. Hvis 'bruk på alle kjøretøy av denne modellen' var valgt, vil dette tilbakestille alle disse kjøretøyene.",
bodyRollLeft = "Flytt til venstre hvis kjøretøyet vipper i kjøreretningen eller hvis det er for stivt/har ingen karosserivipping",
bodyRollRight = "Flytt til høyre hvis kjøretøyet velter i svinger eller har for mye karosserivipping/ikke er stivt nok",
handlingNotApplied = "Endringene i kjøreegenskapene dine har ikke blitt brukt på kjøretøyet.",
continueAreYouSure = "Er du sikker på at du vil fortsette?",
previewRtnToEditor = "Trykk [BACKSPACE] for å gå tilbake til redigeringsverktøyet.",
mechanicDataModeExplain = "Dette kjøretøyets kjøreegenskaper har blitt endret av JG Mechanic. Du kan velge å redigere kjøreegenskapene som de er (alternativ 1), redigere dem uten noen modifikasjoner (alternativ 3), eller kun uten skadeservice (alternativ 2).",
currentHandlingExplain = "Juster kjøretøyets nåværende kjøreegenskaper, inkludert tuning og servicemodifikasjoner.",
ignoreServicingExplain = "Hent kjøretøyets nåværende kjøreegenskaper, men uten skadeservice (hvis aktuelt).",
useBaseHandlingExplain = "Bruk kjøretøyets grunnleggende kjøreegenskaper, uten noen endringer gjort av JG Mechanic.",
applyToModelWarning = "Dette anbefales ikke, da det kan skape høy belastning på serveren din. Eksporter og oppdater heller kjøretøyets handling.meta-fil.",


-- Tuningkategorier
allCategories = "Alle kategorier",
aero = "Aerodynamikk",
transmission = "Girkasse",
traction = "Hjulgrep",
suspension = "Fjæring",
damage = "Skade",
chassis = "Chassis",
engine = "Motor",
brakes = "Bremser",
antiroll = "Stabilisatorstag",
flags = "Flagg",
other = "Annet",
acceleration = "Akselerasjon",
topSpeed = "Toppfart (%s)",
transmissionGearbox = "Girkasse (Gearbox)",
drivetrain = "Drivverk (RWD, AWD, etc.)",
downforce = "Vinge (Marktrykk)",
bodyRoll = "Karosserivipping",

-- Tidtakingsverktøy
ready = "Klar",
recording = "Opptak",
stopVehicle = "Stopp kjøretøy",
idle = "Tomgang",
loading = "Laster...",

-- Varsler
noSavedHandlings = "Ingen lagrede kjøreegenskapskonfigurasjoner",
noResultsFound = "Ingen resultater funnet",
noHandlingChangesMade = "Ingen endringer i kjøreegenskapene er gjort",
handlingSaved = "Kjøreegenskaper lagret",
notInVehicle = "Du er ikke i et kjøretøy",
notCompatibleWithHandlingEditor = "Kjøretøyet er ikke kompatibelt med kjøreegenskapsredigereren",
handlingApplied = "Kjøreegenskapsprofil brukt vellykket",
requiresAdmin = "Du må være admin for å bruke dette",
noPermission = "Du har ikke tillatelse til å bruke dette",
couldNotCreateProfile = "Kunne ikke opprette ny profil",

}
